### ISSUE TITLE
Privacy Policy Link

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexWallet-website#13]
- Add: "Privacy" as a menu item on the top menu
- Create "Privacy Page"
- Design reference: https://www.dexwallet.io/terms-and-conditions/
- Text: https://docs.google.com/document/d/1jp6ufQhbA2S4UaIwJi6GVvFRnPYY7PkBny31sh_v6U0/edit

**Comment by gabcava** [comment]
Add also a link to the newly create "Privacy Page" at the bottom of the page https://www.dexwallet.io/terms-and-conditions/.
adding the text

"Please make sure to consult our Privacy Policy at "....(add new link to the privacy page)
