### ISSUE TITLE
Create "Terms & Conditions" Page

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexWallet-website#4]
**Positions:**
- About
- Blog
- Terms & Conditions
- Contact Us

**HD Design here:**
https://drive.google.com/open?id=1dmYs_mkl9fwsvjbRUGINaDGVY-43-4ey

**For the content, please refer to this other issue:**
https://github.com/Alexintosh/DexWallet/issues/87

**Comment by aesthytik** [comment]
Added T&C page
