### ISSUE TITLE
Modal for Coming soon Android App

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/DexWallet-website#6]
When a user clicks on the Play Store / Apple Store button, if the App is missing, show the following modal.

**HD Design:**
https://drive.google.com/open?id=1k4uTS9tRqqtBIQ8I2S4FHtdDWSqfMgSe

**X close icon:**
https://drive.google.com/open?id=1VMjhM2TZcJgdcW7cruslL_Lx83FbjGaB

Copy following

> 
> The Android App is coming soon!
> Subscibe to our newsletter and be the first to know.

**Comment by aesthytik** [comment]
I updated the landing page and added modal
